version: "3.1"
services:
  backend:
    build: ./backend/
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    working_dir: /app
    tty: true
    networks:
      - dev_network
    # command: bash -c "npm install && npm start"
  mongo:
    image: mongo
    restart: always
    networks:
      - dev_network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_db_data:/data/db
      - ./mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
volumes:
  mongo_db_data:
networks:
  dev_network:
